name: Integration tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache: true

      - uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: '5.0'

      - name: Run tests
        run: TF_ACC=1 go test ./... -v
